#pragma config(Sensor, S2,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//1=black 2=blue 3=green 4=yellow 5=red 6=white 7=brown

task main()
{
   while(true)
   {
      motor[motorB] = 30;
      motor[motorC] = 30;

      if(SensorValue[S2]==1||SensorValue[S3]==1||SensorValue[S4]<50)
      {
         while(SensorValue[S2]!= 2)
         {
            motor[motorB] = -30;
            motor[motorC] = -30;
         }

         if(SensorValue[S2]== 2)
         {
            motor[motorB] = 0;
            motor[motorC] = 0;
            wait1Msec(500);
            motor[motorB] = 15;
            motor[motorC] = 30;
            wait1Msec(500);
         }
       }
       
       if(SensorValue[S2]== 5)   
         {
           while(SensorValue[S2]!=2)
             {
               motor[motorB] = -30;
               motor[motorC] = -30;
            }
            if(SensorValue[S2]==2)
            {
               motor[motorB] = 0;
               motor[motorC] = 0;
               wait1Msec(500);
               playSound(soundBeepBeep);
               wait1Msec(1000);
               motor[motorB] = 15;
               motor[motorC] = 30;
               wait1Msec(500);
            }
         }
      }
 }